[package]
name = "runar"
version = "0.1.0"
authors = ["Daniel Ohlsson <dohlsson89@gmail.com>"]
description = "Watches for changes in files and runs/restarts a program"
documentation = "https://github.com/DOhlsson/runar"
homepage = "https://github.com/DOhlsson/runar"
repository = "https://github.com/DOhlsson/runar"
readme = "README.md"
keywords = ["run", "restart", "watch", "nodemon"]
categories = ["command-line-utilities"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
nix = "0.19"
inotify = "0.9"
clap = "2.33"
walkdir = "2.3"

[dev-dependencies]
assert_cli = "0.5"

[profile.release]
# strip = "symbols" # nightly only
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
